-- Display all customers who have placed an order.
select * 
from customers c
join orders o
on c.customer_id = o.customer_id;

-- Display the customer name, city, order ID, and order amount for every customer who has placed an order.
select 
	c.customer_name,
    c.city,
    o.order_id,
    o.amount
from customers c
join orders o
on c.customer_id = o.customer_id;
-- Find customers who have placed an order with an amount greater than ₹3,000.
select 
	c.customer_name,
    c.city,
    o.order_id,
    o.amount
from customers c
join orders o
on c.customer_id = o.customer_id
where o.amount > 3000;
-- Display all customers who have placed an order, along with their order amount. Show the highest-value orders first.
select 
	c.customer_name,
    c.city,
    o.order_id,
    o.amount
from customers c
join orders o
on c.customer_id = o.customer_id
order by o.amount desc;
-- Find all customers, including customers who have never placed an order.
select 
	c.customer_name,
    c.city,
    o.order_id,
    o.amount
from customers c
left join orders o
on c.customer_id = o.customer_id;
-- Find customers who NEVER ordered
select 
	c.customer_name,
    c.city,
    o.order_id,
    o.amount
from customers c
left join orders o
on c.customer_id = o.customer_id
where o.order_id is null;
-- Find the total number of orders placed by each customer. Include customers who have placed zero orders.
select 
	c.customer_name,
	count(o.customer_id) as total_orders
from customers c
left join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by count(o.customer_id) desc;
-- Find the total amount spent by each customer. Include customers who have never placed an order.
select 
	c.customer_name,
    coalesce(sum(o.amount),0) as total_spent
from customers c
left join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by total_spent desc;
-- Find customers whose total spending is greater than ₹5,000.
select 
	c.customer_name,
    coalesce(sum(o.amount),0) as total_spent
from customers c
left join orders o
on c.customer_id = o.customer_id
group by c.customer_id
having total_spent > 5000
order by total_spent desc;
-- Find all customers who have placed at least one order, and show their total number of orders and total amount spent.
select 
	c.customer_name,
    count(o.customer_id) as total_orders,
    sum(o.amount) as total_spent
from customers c
inner join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by total_orders desc;
-- Display each order along with the customer name and the product name.
select 
	o.*,
	c.customer_name,
    p.product_name
from orders o 
join customers c
on o.customer_id = c.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id;

-- Display each product sold in each order and calculate the revenue generated for that product line.
select 
	o.order_id,
	c.customer_name,
    p.product_name,
    oi.quantity,
    p.unit_price,
    (oi.quantity * p.unit_price) as revenue
from orders o 
join customers c
on o.customer_id = c.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id;

-- Which product categories generated the most revenue?
select 
    p.category,
    sum(oi.quantity * p.unit_price) as total_revenue
from order_items oi 
join products p
on oi.product_id = p.product_id
group by p.category
order by total_revenue desc;
-- Find products that generated more than ₹2,000 in total revenue.
select 
	p.product_name,
    SUM(oi.quantity) AS total_quantity,
    sum(oi.quantity * p.unit_price) as total_revenue
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_id ,p.product_name 
having total_revenue > 2000
order by total_revenue desc;

-- Find the total revenue generated by each customer.
select 
	c.customer_name,
    count(DISTINCT o.order_id) as total_orders,
	sum(oi.quantity * p.unit_price) as revenue
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p 
on oi.product_id = p.product_id
group by c.customer_id;

-- For each customer, find the number of unique products they have purchased.
select 
	c.customer_name,
    count(DISTINCT p.product_id) as unique_products
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p 
on oi.product_id = p.product_id
group by c.customer_id, c.customer_name;

-- Find every customer and the total revenue they generated. Include customers who have never purchased anything.
select 
	c.customer_name,
    coalesce(sum(oi.quantity * p.unit_price), 0) as total_revenue
from customers c
left join orders o
on c.customer_id = o.customer_id
left join order_items oi
on o.order_id = oi.order_id
left join products p
on oi.product_id = p.product_id
group by c.customer_id
order by total_revenue desc;

-- Find all customers who purchased at least one product from the Electronics category.
select
	distinct
	c.customer_name,
	p.product_name,
    p.category
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
where p.category = 'Electronics'
;

-- Find customers who purchased more than one different product.
select
	c.customer_name,
    count(distinct p.product_id) as unique_products
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
group by c.customer_id, c.customer_name
having unique_products > 1
;

-- Display each employee along with their manager's name.
select 
	e.employee_name as employee,
    m.employee_name as manager
from employees e
left join employees m
on e.manager_id = m.employee_id;

-- Find all employees who report directly to Amit.
select 
	e.employee_name as employee
from employees e
left join employees m
on e.manager_id = m.employee_id
where m.employee_name = 'Amit'
;
