USE TEST;
-- UNION
SELECT EMP_NAME AS C_NAME FROM (
SELECT EMP_NAME FROM employees
union
SELECT NAME FROM STUDENT) T;

-- UNION ALL (WITH DUPLICATES)
SELECT EMP_NAME AS C_NAME FROM (
SELECT EMP_NAME FROM employees
union ALL
SELECT NAME FROM STUDENT) T;


