create database skillit;
use skillit;
create table Customers (
	CustomerId int primary key auto_increment,
	CustomerName varchar(100),
	City varchar(100),
	JoinDate date
);

create table Products (
	ProductId int primary key auto_increment,
	ProductName varchar(100),
	Category varchar(100),
	Price decimal(10,2)
);

create table Employees (
	EmployeeId int primary key auto_increment,
	EmployeeName varchar(100),
	Department varchar(100),
	HireDate date
);

create table Orders (
	OrderId int primary key auto_increment,
	CustomerId int,
	OrderDate date,
	EmployeeId int,

CONSTRAINT FK_Orders_Customers
        FOREIGN KEY (CustomerId)
        REFERENCES Customers(CustomerId),

CONSTRAINT FK_Orders_Employees
        FOREIGN KEY (EmployeeId)
        REFERENCES Employees(EmployeeId)
);

create table OrderDetails (
	OrderDetailId int primary key auto_increment,
	OrderId int,
	ProductId int,
	Quantity int,

CONSTRAINT FK_OrderDetails_Orders
        FOREIGN KEY (OrderId)
        REFERENCES Orders(OrderId),
        
CONSTRAINT FK_OrderDetails_Products
        FOREIGN KEY (ProductId)
        REFERENCES Products(ProductId)
);

-- Section 1 
-- 1. Display all orders with customer names.
select 
	o.OrderId,
    o.CustomerId,
    c.CustomerName,
    o.OrderDate,
    o.EmployeeId
from orders o
join customers c 
on o.CustomerId = c.CustomerId;

-- 2. Show product names and quantities for each order.
select 
	o.OrderDetailId,
	p.ProductName,
	o.quantity
from OrderDetails o
inner join products p 
on o.ProductId = p.ProductId;

-- 3. Display employee name who handled each order.
select 
	e.employeeName,
	o.OrderId,
    o.OrderDate
from Orders o
inner join employees e
on o.employeeId = e.employeeId;

-- 4. Show all customers and their orders (including customers without orders).
select 
 c.customerId, 
 c.customerName,
 o.orderId,
 o.orderDate
from customers c
left join orders o
on c.customerId = o.customerId;

-- 5. Display total number of orders handled by each employee.
select 
	e.employeeId, 
    e.employeeName, 
    count(o.orderId) as Total_No_orders
from  employees e 
left join orders o
on e.employeeId = o.employeeId
group by e.employeeId, e.employeeName;

-- Section 2 — Subqueries
-- 6. Find customers who placed more than 1 order.
select 
	customerId 
from orders
group by customerId
having count(customerId) > 1;

select 
	*
from 
customers 
where customerId in (select customerId from orders
group by customerId
having count(customerId) > 1)
;

-- 7. Display products with price higher than the average product price.

select 
	* 
from products
where price > (select avg(price) from products);

-- 8. Find the customer who placed the highest number of orders.
select 
	customerId 
from orders
group by customerId
having count(customerId)
order by count(customerId) desc
limit 1
;

select 
	*
from 
customers 
where customerId = (select customerId from orders
group by customerId
order by count(customerId) desc
limit 1);

-- 9. Show orders where total quantity is greater than the average quantity.
select 
	od.OrderDetailId, 
    od.OrderId, 
    od.ProductId, 
    o.CustomerId, 
    o.OrderDate, 
    o.EmployeeId, 
    od.Quantity 
from orderDetails od
join orders o
on od.orderId = o.orderId
where quantity > (select avg(quantity) from orderdetails);

-- 10. Find employees who handled more orders than the average employee.
-- select * from orders;

select avg(order_count) from 
(select count(employeeId) as order_count 
	from orders
group by employeeId) x;

-- 11. Using CTE, calculate total sales amount for each order.
-- Expected logic:
-- Quantity × Price

with total_sales_amount as (
select 
	od.OrderId, 
    sum(od.Quantity * p.Price) as total_sales
from orderDetails od
join products p 
on od.productId = p.productId
group by od.OrderId
)


select * from total_sales_amount;

-- 12. Using CTE, find customers whose total purchase amount is greater than 20,000.
with customers_total_purchase as (
select 
	o.customerId, 
    sum(od.Quantity * p.Price) as total_amount
from orders o
join orderdetails od
on o.orderId = od.orderId
join products p 
on od.productId = p.productId
group by o.customerId)

select * from customers_total_purchase where total_amount > 20000;

-- 13. Using CTE, display the total revenue generated by each product category.
with revenue_by_category as (
select 
	p.category, 
    sum(od.Quantity * p.Price) as total_amount
from orders o
join orderdetails od
on o.orderId = od.orderId
join products p 
on od.productId = p.productId
group by p.category)

select * from revenue_by_category;

-- 14. Using CTE, find the top 3 customers based on total spending.
with top_customenrs_by_total_spends as (
select 
	c.CustomerId, 
    c.customerName,
    sum(od.Quantity * p.Price) as total_amount
from orders o
join orderdetails od
on o.orderId = od.orderId
join customers c
on o.CustomerId = c.CustomerId
join products p
on od.ProductId = p.ProductId
group by c.CustomerId
)

select * 
from top_customenrs_by_total_spends
order by total_amount desc
limit 3;

-- Section 4
-- 15. Assign rank to customers based on total purchase amount. use RANK()
with top_customenrs_by_total_spends as (
select 
	c.CustomerId, 
    c.customerName,
    sum(od.Quantity * p.Price) as total_amount
from orders o
join orderdetails od
on o.orderId = od.orderId
join customers c
on o.CustomerId = c.CustomerId
join products p
on od.ProductId = p.ProductId
group by c.CustomerId
)

select *, rank() over(order by total_amount desc) as rnk
from top_customenrs_by_total_spends;

-- 16. Display cumulative sales amount by order date. Use: SUM() OVER
with daily_sales_by_orderdate as (
select 
	o.orderDate,
    sum(od.Quantity * p.Price) as daily_sales
from orders o
join orderdetails od
on o.orderId = od.orderId
join customers c
on o.CustomerId = c.CustomerId
join products p
on od.ProductId = p.ProductId
group by o.orderDate)

select 
	orderDate, 
    daily_sales, 
    sum(daily_sales) over (order by orderdate) as cumulative_sales 
from daily_sales_by_orderdate;

-- 17. Display running total of sales for each employee.
select 
	o.employeeId,
    o.orderdate,
    sum(od.Quantity * p.Price) as total_sales,
    sum(sum(od.Quantity * p.Price)) over (partition by o.employeeId  order by o.orderdate ) as running_total
from orders o
join orderdetails od
on o.orderId = od.orderId
join products p
on od.ProductId = p.ProductId
join employees e
on o.employeeId = e.employeeId
group by o.employeeId, o.orderdate;

-- 18. Find the highest priced product in each category.
select * from products;
with ranked_products as (
select 
	productName,
	category,
    price,
    row_number() over (partition by category order by price desc ) as rn
from products)

select * from ranked_products where rn = 1;

-- 21. Find customers who never placed an order.
select * from customers 
where CustomerId not in (select distinct CustomerId from orders);

-- 22. Find the second highest selling product.

with product_sales as (
select 
p.productId,
p.productName,
count(p.productId) as sale_count
from orders o
join orderDetails od
on o.orderId = od.orderId
join products p
on od.productId = p.productId
group by p.productId, p.productName
), ranked_products as (select 
	productId, 
    productName,
    dense_rank() over(order by sale_count desc) as rnk
from product_sales)

select * from ranked_products where rnk = 2;


